services:
  - name: NetworkManager
    mandatory: true
  - name: sddm
    mandatory: true
  - name: tor
    mandatory: true
  - name: nftables
    mandatory: true
  - name: usbguard
    mandatory: false

